apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    component: worker
spec:
  containers:
    - name: worker
      image: syamsuldocker/anomaly
      ports:
        - containerPort: 5000