apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: syamsuldocker/anomaly:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-cluster-ip
            - name: MONGO_PORT
              value: "27017"
